<?php
		$_POST['Carta0']	="";
		$_POST['Carta1']	="";
		$_POST['Carta2']	="";
		$_POST['Carta3']	="";
		$_POST['Carta4']	="";
		$_POST['chofer']	="";
		$_POST['placas']	="";
		$_POST['cliente']	="";
		$_POST['n_c']		="";
		$_POST['Revisado']="";
		$_POST['come']	="";
		$_POST['D']		="";
		$_POST['M']		="";
		$_POST['A']		="";
		$_POST['D_c']		="";
		$_POST['M_c']		="";
		$_POST['A_c']		="";
		$_POST['D_r']		="";
		$_POST['M_r']		="";
		$_POST['A_r']		="";
		$_POST['km_i']	="";
		$_POST['km_f']	="";
		$_POST['hidden_fe']	="";
		$_POST['hidden_v']	="";
		$_POST['hidden_d']	="";
		$_POST['hidden_c']	="";
		$_POST['hidden_c_via']="";
		$_POST['hidden_f']	="";
		$_POST['hidden_r']	="";
		$_POST['hidden_g']	="";
		$_POST['hidden_m']	="";
		$_POST['hidden_ab']	="";
		$_POST['hidden_ac']	="";
		$_POST['hidden_ac_a']	="";
		$_POST['revisado']	="";
		$_POST['flete_r']		="";
		$_POST['comi']		="";
		$_POST['presio_d']	="";
		$libre_v2->borrar('1TEXT');
		$libre_v2->borrar('1TEXT_C');
		$libre_v2->borrar('2TEXT');
		$libre_v2->borrar('2TEXT_C');
		$libre_v2->borrar('3TEXT');
		$libre_v2->borrar('3TEXT_C');
		$libre_v2->borrar('4TEXT');
		$libre_v2->borrar('4TEXT_C');        
		$libre_v2->borrar('4TEXT_VIA');
		$libre_v2->borrar('4TEXT_C_VIA');
		$libre_v2->borrar('5TEXT');
		$libre_v2->borrar('5TEXT_C');
		$libre_v2->borrar('6TEXT');
		$libre_v2->borrar('6TEXT_C');
		$libre_v2->borrar('7TEXT');
		$libre_v2->borrar('7TEXT_C');
		$libre_v2->borrar('8TEXT');
		$libre_v2->borrar('8TEXT_C');
		$libre_v2->borrar('ab_Com');
		$libre_v2->borrar('ab');
		$libre_v2->borrar('ID_ac');
		$libre_v2->borrar('ac');
 ?>
