<?php
$res='';
$res=Presenta3(
$id,$style,$style_t,$title,$col1,$col2
,$t0,$t1,$t2
,$repite,$limite
,$name1,$name2,$name3
,$n_r1,$n_r2
,$title1,$title2
,$max1,$max2
,$style1,$style2
,$final
);
$id=$style=$style_t=$title=$col1=$col2
=$t0=$t1=$t2
=$repite=$limite
=$name1=$name2=$name3
=$n_r1=$n_r2
=$title1=$title2
=$max1=$max2
=$style1=$style2
=$final='';
?>